import {
  FolderKanban,
  Layout,
  Code,
  Bug,
  Rocket,
  Star,
  Heart,
  Zap,
  Globe,
  BookOpen,
  Briefcase,
  Target,
  Shield,
  Lightbulb,
  MessageSquare,
  Package,
  FileText,
  Database,
  Palette,
  Home,
  Users,
  Settings,
  Calendar,
  Clock,
  Camera,
  Music,
  Film,
  Image,
  Monitor,
  Smartphone,
  Cpu,
  HardDrive,
  Cloud,
  Lock,
  Key,
  Mail,
  Send,
  Bell,
  Bookmark,
  Flag,
  Award,
  Trophy,
  Crown,
  Gem,
  Flame,
  Snowflake,
  Sun,
  Moon,
  Compass,
  Map,
  Navigation,
  Plane,
  Car,
  Bike,
  Anchor,
  Building,
  Store,
  Warehouse,
  Hammer,
  Wrench,
  Puzzle,
  Gamepad2,
  Dumbbell,
  GraduationCap,
  Stethoscope,
  Leaf,
  TreePine,
  Flower2,
  Dog,
  Cat,
  Fish,
  Bird,
  Egg,
  Coffee,
  UtensilsCrossed,
  Wine,
  Beaker,
  Microscope,
  TestTube2,
  Atom,
  Binary,
  CircuitBoard,
  Wifi,
  Radio,
  Tv,
  Headphones,
  Speaker,
  Pen,
  Highlighter,
  Eraser,
  Scissors,
  Paperclip,
  FolderOpen,
  Archive,
  Layers,
  Box,
  Gift,
  ShoppingCart,
  CreditCard,
  Banknote,
  PiggyBank,
  BarChart3,
  PieChart,
  TrendingUp,
  Activity,
  Sparkles,
  Wand2,
  type LucideIcon,
} from 'lucide-react'

export const spaceIconMap: Record<string, LucideIcon> = {
  'folder-kanban': FolderKanban,
  layout: Layout,
  code: Code,
  bug: Bug,
  rocket: Rocket,
  star: Star,
  heart: Heart,
  zap: Zap,
  globe: Globe,
  'book-open': BookOpen,
  briefcase: Briefcase,
  target: Target,
  shield: Shield,
  lightbulb: Lightbulb,
  'message-square': MessageSquare,
  package: Package,
  'file-text': FileText,
  database: Database,
  palette: Palette,
  home: Home,
  users: Users,
  settings: Settings,
  calendar: Calendar,
  clock: Clock,
  camera: Camera,
  music: Music,
  film: Film,
  image: Image,
  monitor: Monitor,
  smartphone: Smartphone,
  cpu: Cpu,
  'hard-drive': HardDrive,
  cloud: Cloud,
  lock: Lock,
  key: Key,
  mail: Mail,
  send: Send,
  bell: Bell,
  bookmark: Bookmark,
  flag: Flag,
  award: Award,
  trophy: Trophy,
  crown: Crown,
  gem: Gem,
  flame: Flame,
  snowflake: Snowflake,
  sun: Sun,
  moon: Moon,
  compass: Compass,
  map: Map,
  navigation: Navigation,
  plane: Plane,
  car: Car,
  bike: Bike,
  anchor: Anchor,
  building: Building,
  store: Store,
  warehouse: Warehouse,
  hammer: Hammer,
  wrench: Wrench,
  puzzle: Puzzle,
  gamepad: Gamepad2,
  dumbbell: Dumbbell,
  'graduation-cap': GraduationCap,
  stethoscope: Stethoscope,
  leaf: Leaf,
  'tree-pine': TreePine,
  flower: Flower2,
  dog: Dog,
  cat: Cat,
  fish: Fish,
  bird: Bird,
  egg: Egg,
  coffee: Coffee,
  utensils: UtensilsCrossed,
  wine: Wine,
  beaker: Beaker,
  microscope: Microscope,
  'test-tube': TestTube2,
  atom: Atom,
  binary: Binary,
  'circuit-board': CircuitBoard,
  wifi: Wifi,
  radio: Radio,
  tv: Tv,
  headphones: Headphones,
  speaker: Speaker,
  pen: Pen,
  highlighter: Highlighter,
  eraser: Eraser,
  scissors: Scissors,
  paperclip: Paperclip,
  'folder-open': FolderOpen,
  archive: Archive,
  layers: Layers,
  box: Box,
  gift: Gift,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  banknote: Banknote,
  'piggy-bank': PiggyBank,
  'bar-chart': BarChart3,
  'pie-chart': PieChart,
  'trending-up': TrendingUp,
  activity: Activity,
  sparkles: Sparkles,
  wand: Wand2,
}

export const spaceIconKeys = Object.keys(spaceIconMap) as (keyof typeof spaceIconMap)[]

export function getSpaceIcon(iconName: string): LucideIcon {
  return spaceIconMap[iconName] ?? FolderKanban
}
